Repository thycotic/python-tss-sdk, pull requests merged in 2021-06, with the labels that each got.

#17 Added badges to readme
  README.md
Labels: documentation

#19 Refactoring (fixes #5, #11 and #16)
  README.md
  conftest.py
  thycotic/secrets/server.py
  thycotic/secrets/test_server.py
Labels: documentation, help wanted

#23 Setup release action
  .github/workflows/release.yml
Labels: enhancement
